databases:
  - name: church_voting_app_development
    databaseName: church_voting_app_development
    user: postgres
    plan: free

services:
  - type: web
    name: church_voting_app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -e production" # Specify production environment
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: church_voting_app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
