databases:
  - name: postgres
    databaseName: church_voting_app_development
    user: postgres
    plan: free

  - name: postgres
    databaseName: church_voting_app_production
    user: postgres
    plan: free

services:
  - type: web
    name: postgres
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2