databases:
  - name: church_voting_app_development
    databaseName: church_voting_app_development
    user: wolo
    plan: free
services:
  - type: web
    name: church_voting_app_development
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: church_voting_app_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
