development:
  adapter: postgresql
  encoding: unicode
  database: church_voting_app_development
  pool: 5
  username: postgres
  password: wolo

test:
  <<: *default
  database: church_voting_app_test
  username: postgres
  password: wolo
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: church_voting_app_development
  pool: 5
  username: postgres
  password: wolo


