default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: church_voting_app_development
  username: postgres
  password: wolo
  host: localhost
  port: 5432

test:
  <<: *default
  database: church_voting_app_test
  username: postgres
  password: wolo
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
