default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: wolo
  port: 5432

development:
  <<: *default
  database: church_voting_app_development

test:
  <<: *default
  database: church_voting_app_test

production:
  <<: *default
  database: church_voting_app_production 
  username: postgres  
  password: wolo     
  pool: 5


