default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: wolo
  port: 5432

development:
  <<: *default
  database: church_voting_app_development

test:
  <<: *default
  database: church_voting_app_test

production:
  <<: *default
  database: church_voting_app_production  # Ensure you have the right database name here
  username: postgres  # You can use environment variables for security
  password: wolo      # Use environment variables for security
  port: 5432
  pool: 5


