# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: wolo
  port: 5432

development:
  <<: *default
  database: church_voting_app_development

test:
  <<: *default
  database: church_voting_app_test

production:
  <<: *default
  database: church_voting_app_production
  # Production credentials should be managed securely; consider using environment variables
  username: postgres
  password: wolo
